/*
 * Adaptive frequency-domain demosaicking for Fujifilm X-Trans sensors.
 *
 * Primary references:
 *   M. Rafinazari and E. Dubois, "Demosaicking Algorithm for the
 *   Fujifilm X-Trans Color Filter Array", ICIP 2014, pp. 660-663.
 *   https://doi.org/10.1109/ICIP.2014.7025132
 *
 *   M. Rafi Nazari, "Denoising and Demosaicking of Color Images",
 *   PhD dissertation, University of Ottawa, 2017, section 3.3,
 *   "Demosaicking for the Fujifilm X-Trans pattern", pp. 33-48.
 *   https://ruor.uottawa.ca/items/036d51e5-a089-456a-8e8c-c4a009338f41
 *
 * The references describe Gaussian band-pass filters in the frequency
 * domain. This implementation applies the equivalent finite-support,
 * modulated, separable Gaussian kernels in the spatial domain. It is an
 * independent reconstruction, not source code supplied by the authors.
 * Filter supports and several adaptive-energy parameters are not published;
 * the corresponding choices are documented below and exposed as experimental
 * controls.
 */

#include "alignedbuffer.h"
#include "procparams.h"
#include "rawimage.h"
#include "rawimagesource.h"

#include "rtgui/multilangmgr.h"

#include <algorithm>
#include <array>
#include <cmath>
#include <complex>
#include <cstdlib>
#include <string>
#include <vector>

namespace rtengine
{
namespace
{

using Complex = std::complex<float>;

constexpr double PI = 3.1415926535897932384626433832795;
constexpr int TILE_SIZE = 64;

// Dissertation Figure 3.1 and equation 3.15. Although normally displayed as
// 6x6, the pattern has a 3x6 fundamental region on the lattice of equation
// 3.9; the second half is generated by its (3, 3) translation.
constexpr int CANONICAL_XTRANS[6][6] = {
    {1, 2, 1, 1, 0, 1},
    {0, 1, 0, 2, 1, 2},
    {1, 2, 1, 1, 0, 1},
    {1, 0, 1, 1, 2, 1},
    {2, 1, 2, 0, 1, 0},
    {1, 0, 1, 1, 2, 1}
};

struct Transform {
    int a;
    int b;
    int c;
    int d;
    int ox;
    int oy;
};

struct Frequency {
    double x;
    double y;
};

struct MappedFrequency {
    double x;
    double y;
    double offset;
};

struct Filter {
    std::vector<Complex> horizontal;
    std::vector<Complex> vertical;
    std::array<Complex, 144> demodulation;
    int radius;
};

template<typename T>
struct WorkspaceBuffer {
    AlignedBuffer<T> storage;
    T* data = nullptr;
    size_t capacity = 0;

    void resize(size_t size)
    {
        if (size > capacity && storage.resize(size)) {
            data = storage.data;
            capacity = size;
        }
    }
};

struct ThreadWorkspace {
    std::array<WorkspaceBuffer<Complex>, 12> components;
    std::array<WorkspaceBuffer<float>, 6> energies;
    WorkspaceBuffer<Complex> horizontal;
    WorkspaceBuffer<Complex> filtered;
    WorkspaceBuffer<double> integral;
};

// The twelve nonzero chroma carrier locations d_i from dissertation equation
// 3.11 (q4, q5, q8, q9, and q18 are zero). Frequencies are cycles per pixel.
constexpr std::array<Frequency, 12> CHROMA_FREQUENCIES {{
    { 2.0 / 6.0,  0.0 / 6.0}, // q2
    {-2.0 / 6.0,  0.0 / 6.0}, // q3
    { 2.0 / 6.0,  2.0 / 6.0}, // q6
    {-2.0 / 6.0, -2.0 / 6.0}, // q7
    { 0.0 / 6.0, -2.0 / 6.0}, // q10
    { 0.0 / 6.0,  2.0 / 6.0}, // q11
    { 2.0 / 6.0, -2.0 / 6.0}, // q12
    {-2.0 / 6.0,  2.0 / 6.0}, // q13
    { 3.0 / 6.0, -1.0 / 6.0}, // q14
    {-1.0 / 6.0,  3.0 / 6.0}, // q15
    { 3.0 / 6.0,  1.0 / 6.0}, // q16
    { 1.0 / 6.0,  3.0 / 6.0}  // q17
}};

// Dissertation equations 3.35-3.37 define fL, fC1, and fC2. The component
// relationships listed immediately after equation 3.37 give
// q_i = C1_COEFFICIENTS[i] * fC1 + C2_COEFFICIENTS[i] * fC2.
constexpr double SQRT3 = 1.7320508075688772935;
const std::array<Complex, 12> C1_COEFFICIENTS {{
    { 1.f / 9.f,  static_cast<float>(SQRT3 / 9.0)},
    { 1.f / 9.f, -static_cast<float>(SQRT3 / 9.0)},
    {-2.f / 9.f,  static_cast<float>(2.0 * SQRT3 / 9.0)},
    {-2.f / 9.f, -static_cast<float>(2.0 * SQRT3 / 9.0)},
    { 1.f / 9.f, -static_cast<float>(SQRT3 / 9.0)},
    { 1.f / 9.f,  static_cast<float>(SQRT3 / 9.0)},
    { 4.f / 9.f,  0.f},
    { 4.f / 9.f,  0.f},
    {0.f, 0.f}, {0.f, 0.f}, {0.f, 0.f}, {0.f, 0.f}
}};

const std::array<Complex, 12> C2_COEFFICIENTS {{
    {0.f, 0.f}, {0.f, 0.f}, {0.f, 0.f}, {0.f, 0.f},
    {0.f, 0.f}, {0.f, 0.f}, {0.f, 0.f}, {0.f, 0.f},
    {-1.f / 3.f, -static_cast<float>(SQRT3 / 3.0)},
    { 1.f / 3.f,  static_cast<float>(SQRT3 / 3.0)},
    {-1.f / 3.f,  static_cast<float>(SQRT3 / 3.0)},
    { 1.f / 3.f, -static_cast<float>(SQRT3 / 3.0)}
}};

inline int modulo(int value, int modulus)
{
    const int result = value % modulus;
    return result < 0 ? result + modulus : result;
}

inline int mirror(int value, int size)
{
    if (size <= 1) {
        return 0;
    }

    const int period = 2 * size;
    value = modulo(value, period);
    return value < size ? value : period - value - 1;
}

bool findTransform(const int actual[6][6], Transform& result)
{
    // Cameras and raw decoders may expose a translated, rotated, or reflected
    // representation of Figure 3.1. This implementation detail is not part of
    // the dissertation; it maps that representation back to its coordinate
    // system before applying the published carrier locations.
    constexpr int matrices[8][4] = {
        { 1,  0,  0,  1}, { 0, -1,  1,  0},
        {-1,  0,  0, -1}, { 0,  1, -1,  0},
        {-1,  0,  0,  1}, { 1,  0,  0, -1},
        { 0,  1,  1,  0}, { 0, -1, -1,  0}
    };

    for (const auto& matrix : matrices) {
        for (int oy = 0; oy < 6; ++oy) {
            for (int ox = 0; ox < 6; ++ox) {
                bool matches = true;

                for (int y = 0; y < 6 && matches; ++y) {
                    for (int x = 0; x < 6; ++x) {
                        const int cx = modulo(matrix[0] * x + matrix[1] * y + ox, 6);
                        const int cy = modulo(matrix[2] * x + matrix[3] * y + oy, 6);

                        if (actual[y][x] != CANONICAL_XTRANS[cy][cx]) {
                            matches = false;
                            break;
                        }
                    }
                }

                if (matches) {
                    result = {matrix[0], matrix[1], matrix[2], matrix[3], ox, oy};
                    return true;
                }
            }
        }
    }

    return false;
}

MappedFrequency mapFrequency(const Frequency& frequency, const Transform& transform)
{
    // If canonical coordinates are c = A*x + o, the modulation
    // exp(j*2*pi*d.c) becomes exp(j*2*pi*((A^T*d).x + d.o)).
    return {
        frequency.x * transform.a + frequency.y * transform.c,
        frequency.x * transform.b + frequency.y * transform.d,
        frequency.x * transform.ox + frequency.y * transform.oy
    };
}

Filter makeFilter(const MappedFrequency& frequency, double sigma, int radius)
{
    sigma = std::max(0.01, sigma);
    radius = std::max(1, radius);

    Filter filter;
    filter.radius = radius;
    filter.horizontal.resize(2 * radius + 1);
    filter.vertical.resize(2 * radius + 1);

    std::vector<double> gaussian(2 * radius + 1);
    double sum = 0.0;

    // Section 3.3, pp. 36-37: three 2D Gaussian filters, with published
    // sigma=2.32 in both dimensions, are modulated to the chroma carriers.
    // Their finite support was selected experimentally but not published.
    for (int k = -radius; k <= radius; ++k) {
        const double value = std::exp(-0.5 * k * k / (sigma * sigma));
        gaussian[k + radius] = value;
        sum += value;
    }

    for (int k = -radius; k <= radius; ++k) {
        const float amplitude = static_cast<float>(gaussian[k + radius] / sum);
        const double phaseX = 2.0 * PI * frequency.x * k;
        const double phaseY = 2.0 * PI * frequency.y * k;
        filter.horizontal[k + radius] = amplitude * Complex(std::cos(phaseX), std::sin(phaseX));
        filter.vertical[k + radius] = amplitude * Complex(std::cos(phaseY), std::sin(phaseY));
    }

    // Equations 3.17 and 3.38-3.43: after band-pass extraction, translate the
    // carrier back to baseband. A 12x12 phase table covers all half-carrier
    // phases used by both reconstruction and energy filters.
    for (int y = 0; y < 12; ++y) {
        for (int x = 0; x < 12; ++x) {
            const double phase = -2.0 * PI * (frequency.x * x + frequency.y * y + frequency.offset);
            filter.demodulation[y * 12 + x] = Complex(std::cos(phase), std::sin(phase));
        }
    }

    return filter;
}

void filterTile(
    const array2D<float>& source,
    int width,
    int height,
    int x0,
    int y0,
    int tileWidth,
    int tileHeight,
    const Filter& filter,
    WorkspaceBuffer<Complex>& horizontal,
    WorkspaceBuffer<Complex>& output)
{
    // Spatial-domain equivalent of the frequency-domain extraction in
    // equations 3.17-3.18. Mirroring supplies samples for the unpublished
    // finite support without creating tile-boundary discontinuities.
    const int radius = filter.radius;
    const int extendedHeight = tileHeight + 2 * radius;
    horizontal.resize(static_cast<size_t>(extendedHeight) * tileWidth);
    output.resize(static_cast<size_t>(tileWidth) * tileHeight);

    for (int ey = 0; ey < extendedHeight; ++ey) {
        const int y = y0 + ey - radius;
        const int sy = mirror(y, height);

        for (int tx = 0; tx < tileWidth; ++tx) {
            const int x = x0 + tx;
            Complex value(0.f, 0.f);

            for (int k = -radius; k <= radius; ++k) {
                value += source[sy][mirror(x - k, width)] * filter.horizontal[k + radius];
            }

            horizontal.data[static_cast<size_t>(ey) * tileWidth + tx] = value;
        }
    }

    for (int ty = 0; ty < tileHeight; ++ty) {
        const int y = y0 + ty;

        for (int tx = 0; tx < tileWidth; ++tx) {
            const int x = x0 + tx;
            Complex value(0.f, 0.f);

            for (int k = -radius; k <= radius; ++k) {
                value += horizontal.data[static_cast<size_t>(ty + radius - k) * tileWidth + tx]
                       * filter.vertical[k + radius];
            }

            output.data[static_cast<size_t>(ty) * tileWidth + tx] =
                value * filter.demodulation[modulo(y, 12) * 12 + modulo(x, 12)];
        }
    }
}

void energyTile(
    const array2D<float>& source,
    int width,
    int height,
    int x0,
    int y0,
    int tileWidth,
    int tileHeight,
    int boxRadius,
    const Filter& filter,
    WorkspaceBuffer<Complex>& horizontal,
    WorkspaceBuffer<Complex>& filtered,
    WorkspaceBuffer<double>& integral,
    WorkspaceBuffer<float>& output)
{
    // Dissertation equations 3.29-3.30: filter at the midpoint between luma
    // and a chroma carrier, square its response, then locally average it. The
    // dissertation uses a 5x5 moving average; boxRadius=2 reproduces it.
    const int extendedWidth = tileWidth + 2 * boxRadius;
    const int extendedHeight = tileHeight + 2 * boxRadius;
    filterTile(source, width, height, x0 - boxRadius, y0 - boxRadius,
               extendedWidth, extendedHeight, filter, horizontal, filtered);

    const size_t integralSize = static_cast<size_t>(extendedWidth + 1) * (extendedHeight + 1);
    integral.resize(integralSize);
    std::fill(integral.data, integral.data + integralSize, 0.0);

    for (int y = 0; y < extendedHeight; ++y) {
        double rowSum = 0.0;
        for (int x = 0; x < extendedWidth; ++x) {
            rowSum += std::norm(filtered.data[static_cast<size_t>(y) * extendedWidth + x]);
            integral.data[static_cast<size_t>(y + 1) * (extendedWidth + 1) + x + 1] =
                integral.data[static_cast<size_t>(y) * (extendedWidth + 1) + x + 1] + rowSum;
        }
    }

    output.resize(static_cast<size_t>(tileWidth) * tileHeight);
    const int diameter = 2 * boxRadius + 1;
    const double normalization = 1.0 / (diameter * diameter);

    for (int y = 0; y < tileHeight; ++y) {
        const int y1 = y;
        const int y2 = y + 2 * boxRadius + 1;
        for (int x = 0; x < tileWidth; ++x) {
            const int x1 = x;
            const int x2 = x + 2 * boxRadius + 1;
            const double sum =
                integral.data[static_cast<size_t>(y2) * (extendedWidth + 1) + x2]
              - integral.data[static_cast<size_t>(y1) * (extendedWidth + 1) + x2]
              - integral.data[static_cast<size_t>(y2) * (extendedWidth + 1) + x1]
              + integral.data[static_cast<size_t>(y1) * (extendedWidth + 1) + x1];
            output.data[static_cast<size_t>(y) * tileWidth + x] = static_cast<float>(sum * normalization);
        }
    }
}

template<size_t N>
std::array<float, N> inverseEnergyWeights(const std::array<float, N>& energy, double floorPercent)
{
    // Equation 3.30 assigns weight inversely to overlap energy and normalizes
    // the weights to sum to one. The percentage floor and exact-zero behavior
    // below are numerical extensions; neither is specified in the references.
    std::array<float, N> result {};
    const float maximum = *std::max_element(energy.begin(), energy.end());

    if (!(maximum > 0.f) || !std::isfinite(maximum)) {
        result.fill(1.f / N);
        return result;
    }

    const float floor = static_cast<float>(std::max(0.0, floorPercent) * 0.01) * maximum;
    std::array<float, N> effective {};
    int zeroCount = 0;

    for (size_t i = 0; i < N; ++i) {
        effective[i] = std::max(energy[i], floor);
        if (!(effective[i] > 0.f)) {
            ++zeroCount;
        }
    }

    if (zeroCount) {
        for (size_t i = 0; i < N; ++i) {
            result[i] = effective[i] > 0.f ? 0.f : 1.f / zeroCount;
        }
        return result;
    }

    const float minimum = *std::min_element(effective.begin(), effective.end());
    float sum = 0.f;

    for (size_t i = 0; i < N; ++i) {
        result[i] = minimum / effective[i];
        sum += result[i];
    }

    for (float& value : result) {
        value /= sum;
    }

    return result;
}

float normalizedC1(const std::array<Complex, 12>& q, const std::array<float, 4>& weights)
{
    // Conjugate-pair formulation of dissertation equation 3.47. Equations
    // 3.41-3.43 explain why each pair sum is real when symmetric filters are
    // used. The scale factors invert the pair coefficients following 3.43.
    const float s23 = (q[0] + q[1]).real();
    const float s67 = (q[2] + q[3]).real();
    const float s1011 = (q[4] + q[5]).real();
    const float s1213 = (q[6] + q[7]).real();

    return 4.5f * weights[0] * s23
         - 2.25f * weights[1] * s67
         + 4.5f * weights[2] * s1011
         + 1.125f * weights[3] * s1213;
}

float normalizedC2(const std::array<Complex, 12>& q, const std::array<float, 2>& weights)
{
    // Conjugate-pair formulation of dissertation equation 3.49.
    return -1.5f * weights[0] * (q[8] + q[10]).real()
           + 1.5f * weights[1] * (q[9] + q[11]).real();
}

#ifdef BENCHMARK
float literalC1(const std::array<Complex, 12>& q, const std::array<float, 4>& weights)
{
    // Literal interpretation of the earlier adaptive update, equation 3.31.
    // It is retained only in benchmark builds because that equation combines
    // components with different gains without the normalization of 3.47.
    const Complex q2 = weights[0] * q[0] + weights[1] * q[2]
                     + weights[2] * q[4] + weights[3] * q[6];
    return (q2 / C1_COEFFICIENTS[0]).real();
}
#endif

} // namespace

bool RawImageSource::rafinazari_xtrans_interpolate(const procparams::RAWParams::XTransSensor& params)
{
    int xtrans[6][6];
    ri->getXtransMatrix(xtrans);

    Transform transform {};
    if (!findTransform(xtrans, transform)) {
        return false;
    }

    if (plistener) {
        plistener->setProgressStr(Glib::ustring::compose(M("TP_RAW_DMETHOD_PROGRESSBAR"), M("TP_RAW_RAFINAZARIADAPTIVE")));
        plistener->setProgress(0.0);
    }

    const auto clampInt = [](int value, int minimum, int maximum) {
        return std::max(minimum, std::min(maximum, value));
    };
    const auto clampDouble = [](double value, double minimum, double maximum) {
        return std::max(minimum, std::min(maximum, value));
    };
    const double reconstructionSigma = clampDouble(params.rafinazariSigma, 0.5, 5.0);
    const double energySigma = clampDouble(params.rafinazariEnergySigma, 0.5, 5.0);
    const int energyRadius = clampInt(params.rafinazariEnergyRadius, 1, 24);
    const int energyBoxRadius = clampInt(params.rafinazariEnergyBoxRadius, 0, 12);
    const double energyFloor = clampDouble(params.rafinazariEnergyFloor, 0.0, 10.0);
    const int radii[3] = {
        clampInt(params.rafinazariNearRadius, 1, 24),
        clampInt(params.rafinazariMiddleRadius, 1, 24),
        clampInt(params.rafinazariFarRadius, 1, 24)
    };

    std::array<Filter, 12> chromaFilters;
    for (size_t i = 0; i < chromaFilters.size(); ++i) {
        // The three groups are exactly those specified on dissertation p. 37:
        // q2/q3/q10/q11, q6/q7/q12/q13, and q14/q15/q16/q17.
        const int group = (i == 0 || i == 1 || i == 4 || i == 5) ? 0 : (i < 8 ? 1 : 2);
        chromaFilters[i] = makeFilter(mapFrequency(CHROMA_FREQUENCIES[i], transform),
                                      reconstructionSigma, radii[group]);
    }

    // Section 3.3, pp. 39-40 and equations 3.29-3.30: estimate overlap at the
    // midpoint between luma and one representative of each conjugate pair.
    // q2, q6, q10, and q12 drive fC1; q14 and q15 drive fC2.
    constexpr int ENERGY_COMPONENTS[6] = {0, 2, 4, 6, 8, 9};
    std::array<Filter, 6> energyFilters;
    for (size_t i = 0; i < energyFilters.size(); ++i) {
        Frequency midpoint = CHROMA_FREQUENCIES[ENERGY_COMPONENTS[i]];
        midpoint.x *= 0.5;
        midpoint.y *= 0.5;
        energyFilters[i] = makeFilter(mapFrequency(midpoint, transform),
                                      energySigma, energyRadius);
    }

    const int tilesX = (W + TILE_SIZE - 1) / TILE_SIZE;
    const int tilesY = (H + TILE_SIZE - 1) / TILE_SIZE;

#ifdef BENCHMARK
    const char* variant = std::getenv("RT_RAFINAZARI_VARIANT");
    const bool useLiteral = variant && std::string(variant) == "literal";
#endif

#ifdef _OPENMP
    #pragma omp parallel
#endif
    {
        ThreadWorkspace workspace;

#ifdef _OPENMP
        #pragma omp for schedule(dynamic, 1) collapse(2)
#endif
        for (int tileY = 0; tileY < tilesY; ++tileY) {
            for (int tileX = 0; tileX < tilesX; ++tileX) {
                const int x0 = tileX * TILE_SIZE;
                const int y0 = tileY * TILE_SIZE;
                const int tileWidth = std::min(TILE_SIZE, W - x0);
                const int tileHeight = std::min(TILE_SIZE, H - y0);
                const size_t pixelCount = static_cast<size_t>(tileWidth) * tileHeight;

                for (size_t i = 0; i < workspace.components.size(); ++i) {
                    filterTile(rawData, W, H, x0, y0, tileWidth, tileHeight,
                               chromaFilters[i], workspace.horizontal, workspace.components[i]);
                }

                for (size_t i = 0; i < workspace.energies.size(); ++i) {
                    energyTile(rawData, W, H, x0, y0, tileWidth, tileHeight,
                               energyBoxRadius, energyFilters[i], workspace.horizontal,
                               workspace.filtered, workspace.integral, workspace.energies[i]);
                }

                for (size_t index = 0; index < pixelCount; ++index) {
                    std::array<Complex, 12> q;
                    for (size_t i = 0; i < q.size(); ++i) {
                        q[i] = workspace.components[i].data[index];
                    }

                    const std::array<float, 4> c1Energy {{
                        workspace.energies[0].data[index], workspace.energies[1].data[index],
                        workspace.energies[2].data[index], workspace.energies[3].data[index]
                    }};
                    const std::array<float, 2> c2Energy {{
                        workspace.energies[4].data[index], workspace.energies[5].data[index]
                    }};
                    const auto c1Weights = inverseEnergyWeights(c1Energy, energyFloor);
                    const auto c2Weights = inverseEnergyWeights(c2Energy, energyFloor);

                    // Production uses the normalized conjugate-pair equations
                    // 3.47 and 3.49. Equation 3.31 remains benchmark-only.
                    float c1;
#ifdef BENCHMARK
                    c1 = useLiteral ? literalC1(q, c1Weights) : normalizedC1(q, c1Weights);
#else
                    c1 = normalizedC1(q, c1Weights);
#endif
                    const float c2 = normalizedC2(q, c2Weights);

                    const int tx = static_cast<int>(index % tileWidth);
                    const int ty = static_cast<int>(index / tileWidth);
                    const int x = x0 + tx;
                    const int y = y0 + ty;

                    float modulatedChroma = 0.f;
                    for (size_t i = 0; i < q.size(); ++i) {
                        const Complex reconstructed = C1_COEFFICIENTS[i] * c1 + C2_COEFFICIENTS[i] * c2;
                        const Complex modulation = std::conj(chromaFilters[i].demodulation[modulo(y, 12) * 12 + modulo(x, 12)]);
                        modulatedChroma += (reconstructed * modulation).real();
                    }

                    // Dissertation equation 3.50: recover baseband luma by
                    // subtracting all reconstructed modulated chroma carriers
                    // from the CFA signal at the measured sample.
                    const float luma = rawData[y][x] - modulatedChroma;

                    // Dissertation equation 3.51: inverse transform from
                    // (fL, fC1, fC2) to the complete linear RGB estimate.
                    float r = luma - (10.f / 9.f) * c1 - 2.f * c2;
                    float g = luma + (8.f / 9.f) * c1;
                    float b = luma - (10.f / 9.f) * c1 + 2.f * c2;

                    if (!std::isfinite(r) || !std::isfinite(g) || !std::isfinite(b)) {
                        r = g = b = rawData[y][x];
                    }

                    red[y][x] = r;
                    green[y][x] = g;
                    blue[y][x] = b;
                }
            }
        }
    }

    if (plistener) {
        plistener->setProgress(1.0);
    }

    return true;
}

} // namespace rtengine
